#Put quiver preview near the center of the screen, rather than edge of the screen
previewOnCenter = true
#Show arrow quick swap only when shift is pressed
showArrowOnlyWithShift = false
#Show arrow quick swap only when shift is pressed
showToolOnlyWithShift = true
#Show arrow quick swap only when shift is pressed
showArmorOnlyWithShift = true

